<?php
/**
 * Import Functions
 *
 * These functions are used for importing data into Intercessor.
 *
 * @package     Intercessor
 * @subpackage  Admin/Import
 * @copyright   Copyright (c) 2019, Victor Aigbeghian
 * @license     http://opensource.org/licenses/GPL-3.0 GNU Public License
 */

// Exit if accessed directly.
defined( 'ABSPATH' ) || exit;

/**
 * Upload an import file with ajax
 *
 * @since 0.9.5
 * @return void
 */
function intercessor_do_ajax_import_file_upload() {

	if ( ! function_exists( 'wp_handle_upload' ) ) {
		require_once ABSPATH . 'wp-admin/includes/file.php';
	}

	// Load main class.
//	require_once INTERCESSOR_DIR . 'src/admin/tools/import/class-batch-import.php';

	// Verify nonce.
	if ( ! wp_verify_nonce( $_REQUEST['intercessor_ajax_import'], 'intercessor_ajax_import' ) ) {
		wp_send_json_error(
			array(
				'error' => esc_html__( 'Nonce verification failed', 'intercessor' ),
			)
		);
	}

	// Verify if all parameters are met.
	if ( empty( $_POST['intercessor-import-class'] ) ) {
		wp_send_json_error(
			array(
				'error'   => esc_html__( 'Missing import parameters. Import class must be specified.', 'intercessor' ),
				'request' => $_REQUEST,
			)
		);
	}

	// Verify the file is properly included for upload.
	if ( empty( $_FILES['intercessor-import-file'] ) ) {
		wp_send_json_error(
			array(
				'error'   => esc_html__( 'Missing import file. Please provide an import file.', 'intercessor' ),
				'request' => $_REQUEST,
			)
		);
	}

	// Acceptable file types.
	$accepted_mime_types = array(
		'text/csv',
		'text/comma-separated-values',
		'text/plain',
		'text/anytext',
		'text/*',
		'text/plain',
		'text/anytext',
		'text/*',
		'application/csv',
		'application/excel',
		'application/vnd.ms-excel',
		'application/vnd.msexcel',
	);

	if ( empty( $_FILES['intercessor-import-file']['type'] )
		|| ! in_array( strtolower( $_FILES['intercessor-import-file']['type'] ), $accepted_mime_types, true ) ) {
		wp_send_json_error(
			array(
				'error'   => esc_html__( 'The file you uploaded does not appear to be a CSV file.', 'intercessor' ),
				'request' => $_REQUEST,
			)
		);
	}

	if ( ! file_exists( $_FILES['intercessor-import-file']['tmp_name'] ) ) {
		wp_send_json_error(
			array(
				'error'   => esc_html__( 'Something went wrong during the upload process, please try again.', 'intercessor' ),
				'request' => $_REQUEST,
			)
		);
	}

	// Let WordPress import file. We will remove it after import is complete.
	$import_file = wp_handle_upload( $_FILES['intercessor-import-file'], array( 'test_form' => false ) );

	if ( $import_file && empty( $import_file['error'] ) ) {
		
		/**
		 * Fires before processing the file upload.
		 *
		 * @param string $import_class The import class $_POST.
		 *
		 * @since 0.9.5
		 */
		do_action( 'intercessor_batch_import_class_include', $_POST['intercessor-import-class'] );

		$import = new $_POST['intercessor-import-class']( $import_file['file'] );

		if ( ! $import->can_import() ) {
			wp_send_json_error(
				array(
					'error' => esc_html__( 'You do not have permission to import data', 'intercessor' ),
				)
			);
		}

		wp_send_json_success(
			array(
				'form'      => $_POST,
				'class'     => $_POST['intercessor-import-class'],
				'upload'    => $import_file,
				'first_row' => $import->get_first_row(),
				'columns'   => $import->get_columns(),
				'nonce'     => wp_create_nonce( 'intercessor_ajax_import', 'intercessor_ajax_import' ),
			)
		);
	} else {

		/**
		 * Error generated by _wp_handle_upload()
		 *
		 * @see _wp_handle_upload() in wp-admin/src/file.php
		 */

		wp_send_json_error( array( 'error' => $import_file['error'] ) );
	}

	exit;

}
add_action( 'intercessor_upload_import_file', 'intercessor_do_ajax_import_file_upload' );

/**
 * Process batch imports via ajax
 *
 * @since 0.9.5
 * @return void
 */
function intercessor_do_ajax_import() {

	require_once INTERCESSOR_DIR . 'src/Admin/Tools/Import/Prayers.php';

	if ( ! wp_verify_nonce( $_REQUEST['nonce'], 'intercessor_ajax_import' ) ) {
		wp_send_json_error( array( 'error' => esc_html__( 'Nonce verification failed', 'intercessor' ), 'request' => $_REQUEST ) );
	}

	if ( empty( $_REQUEST['class'] ) ) {
		wp_send_json_error( array( 'error' => esc_html__( 'Missing import parameters. Import class must be specified.', 'intercessor' ), 'request' => $_REQUEST ) );
	}

	if ( ! file_exists( $_REQUEST['upload']['file'] ) ) {
		wp_send_json_error( array( 'error' => esc_html__( 'Something went wrong during the upload process, please try again.', 'intercessor' ), 'request' => $_REQUEST ) );
	}

	do_action( 'intercessor_batch_import_class_include', $_REQUEST['class'] );

	$step     = absint( $_REQUEST['step'] );
	$class    = $_REQUEST['class'];
	$import   = new $class( $_REQUEST['upload']['file'], $step );

	if ( ! $import->can_import() ) {

		wp_send_json_error( array( 'error' => esc_html__( 'You do not have permission to import data', 'intercessor' ) ) );

	}

	parse_str( $_REQUEST['mapping'], $map );

	$import->map_fields( $map['intercessor-import-field'] );

	$ret = $import->process_step( $step );

	$percentage = $import->get_percentage_complete();

	if ( $ret ) {

		$step += 1;
		wp_send_json_success( array(
			'step'       => $step,
			'percentage' => $percentage,
			'columns'    => $import->get_columns(),
			'mapping'    => $import->field_mapping,
			'total'      => $import->total
		) );

	} elseif ( true === $import->is_empty ) {

		wp_send_json_error( array(
			'error' => esc_html__( 'No data found for import parameters', 'intercessor' )
		) );

	} else {

		wp_send_json_success( array(
			'step'    => 'done',
			'message' => sprintf(
				esc_html__( 'Import complete! <a href="%s">View imported %s</a>.', 'intercessor' ),
				$import->get_list_table_url(),
				$import->get_import_type_label()
			)
		) );

	}
}
add_action( 'wp_ajax_intercessor_do_ajax_import', 'intercessor_do_ajax_import' );

/**
 * Add a hook allowing extensions to register a hook on the batch export process
 *
 * @since  0.9.5
 * @return void
 */
function intercessor_register_batch_importers() {
	if ( is_admin() ) {
		do_action( 'intercessor_register_batch_importer' );
	}
}
add_action( 'plugins_loaded', 'intercessor_register_batch_importers' );

/**
 * Register the prayers batch importer
 *
 * @since  0.9.5
 */
function intercessor_register_prayers_batch_import() {
	add_action( 'intercessor_batch_import_class_include', 'intercessor_include_prayers_batch_import_processer', 10 );
}
add_action( 'intercessor_register_batch_importer', 'intercessor_register_prayers_batch_import', 10 );

/**
 * Loads the prayers batch process if needed
 *
 * @since  0.9.5
 * @param  string $class The class being requested to run for the batch import
 * @return void
 */
function intercessor_include_prayers_batch_import_processer( $class ) {

	if ( 'Intercessor\Admin\Tools\Import\Prayers' === $class ) {
		require_once INTERCESSOR_DIR . 'src/Admin/Tools/Import/Prayers.php';
	}

}