<?php
/**
 * Exports Actions and Functions
 *
 * These are actions related to exporting data from Intercessor.
 *
 * @package     Intercessor
 * @subpackage  Admin/Export
 * @copyright   Copyright (c) 2019, Victor Aigbeghian
 * @license     http://opensource.org/licenses/GPL-3.0.php GNU Public License
 * @since       0.9.5
 */

use Intercessor\Admin\Tools\Export;
use Intercessor\Admin\Tools\Export\Batch_Prayers;

// Exit if accessed directly.
defined( 'ABSPATH' ) || exit;

/**
 * Process the prayer file generated by a batch export.
 *
 * @since 0.9.5
 */
function intercessor_process_batch_export_prayer() {
	if ( ! wp_verify_nonce( $_REQUEST['nonce'], 'intercessor-batch-export' ) ) {
		wp_die(
			esc_html__( 'Nonce verification failed', 'intercessor' ),
			esc_html__( 'Error', 'intercessor' ),
			array( 'response' => 403 )
		);
	}

	require_once INTERCESSOR_DIR . 'src/Admin/Tools/Export/Batch.php';

	do_action( 'intercessor_batch_export_class_include', $_REQUEST['class'] );

	// @TODO
//	$export = new $_REQUEST['class']();
	$export = new Batch_Prayers();

	// Process export.
	$export->export();
}
add_action( 'intercessor_prayer_batch_export', 'intercessor_process_batch_export_prayer' );

/**
 * Export all the Requesters to a CSV file.
 *
 * Note: The WordPress Database API is being used directly for performance
 * reasons (workaround of calling all posts and fetch data respectively)
 *
 * @since 0.9.5
 * @return void
 */
function intercessor_export_all_requesters() {
//	require_once INTERCESSOR_DIR . 'src/Admin/Tools/Export/Batch_Requesters.php';

	$requester_export = new Intercessor\Admin\Tools\Export\Batch_Requesters();

	$requester_export->export();
}
add_action( 'intercessor_requesters_export', 'intercessor_export_all_requesters' );

/**
 * Add a hook allowing extensions to register a hook on the batch export process
 *
 * @since  0.9.5
 * @return void
 */
function intercessor_register_batch_exporters() {
	if ( is_admin() ) {
		do_action( 'intercessor_register_batch_exporter' );
	}
}
add_action( 'plugins_loaded', 'intercessor_register_batch_exporters', 99 );

/**
 * Register the prayers batch exporter
 * @since  0.9.5
 */
function intercessor_register_prayers_batch_export() {
	add_action( 'intercessor_batch_export_class_include', 'intercessor_include_prayers_batch_processor', 10, 1 );
}
add_action( 'intercessor_register_batch_exporter', 'intercessor_register_prayers_batch_export', 10 );

/**
 * Loads the prayers batch processor if needed.
 *
 * @since 0.9.5
 *
 * @param string $class The class being requested to run for the batch export
 */
function intercessor_include_prayers_batch_processor( $class ) {
	if ( 'Intercessor\Admin\Tools\Export\Batch_Prayers' === $class ) {
		require_once INTERCESSOR_DIR . 'src/Admin/Tools/Export/Batch_Prayers.php';
	}
}

/**
 * Register the Requesters batch exporter.
 *
 * @since 0.9.5
 */
function intercessor_register_requesters_batch_export() {
	add_action( 'intercessor_batch_export_class_include', 'intercessor_include_requesters_batch_processor', 10, 1 );
}
add_action( 'intercessor_register_batch_exporter', 'intercessor_register_requesters_batch_export', 10 );

/**
 * Loads the Requesters batch processor if needed.
 *
 * @since 0.9.5
 *
 * @param string $class The class being requested to run for the batch export.
 */
function intercessor_include_requesters_batch_processor( $class ) {
	if ( 'IPR_Batch_Requesters_Export' === $class ) {
		require_once INTERCESSOR_DIR . 'src/Admin/Tools/Export/Batch_Requesters.php';
	}
}

/**
 * Register the prayers and prayed report batch exporter.
 *
 * @since 0.9.5
 */
function intercessor_register_prayers_and_counts_batch_export() {
	add_action( 'intercessor_batch_export_class_include', 'intercessor_include_prayers_and_counts_batch_processor', 10, 1 );
}
add_action( 'intercessor_register_batch_exporter', 'intercessor_register_prayers_and_counts_batch_export', 10 );

/**
 * Loads the prayers and prayed batch process if needed.
 *
 * @since 0.9.5
 *
 * @param string $class The class being requested to run for the batch export
 */
function intercessor_include_prayers_and_counts_batch_processor( $class ) {
	if ( 'Batch_History' === $class ) {
		require_once INTERCESSOR_DIR . 'src/Admin/Tools/Export/Batch_History.php';
	}
}

/**
 * Export Intercessor settings to a JSON file
 *
 * Note: The WordPress Database API is being used directly for performance
 * reasons (workaround of calling all posts and fetch data respectively)
 *
 * @since 0.9.5
 * @return void
 */
function intercessor_export_all_settings() {

	// Bail if no nonce.
	if ( empty( $_POST['intercessor_export_nonce'] ) ) {
		return;
	}

	// Bail if nonce does not verify.
	if ( ! wp_verify_nonce( $_POST['intercessor_export_nonce'], 'intercessor_export_nonce' ) ) {
		return;
	}

	// Bail if user cannot manage prayer.
	if ( ! current_user_can( 'manage_options' ) ) {
		return;
	}
	require_once INTERCESSOR_DIR . 'src/Admin/Tools/Export/Settings.php';

	$settings_export = new Intercessor\Admin\Tools\Export\Settings();

	$settings_export->export();

	exit;
}
add_action( 'intercessor_export_settings', 'intercessor_export_all_settings' );

/**
 * Process batch exports via AJAX.
 *
 * @since 0.9.5
 */
function intercessor_do_ajax_export() {
	require_once INTERCESSOR_DIR . 'src/admin/tools/export/Batch.php';

	parse_str( $_POST['form'], $form );

	$_REQUEST = $form;
	$form     = (array) $form;
/*	if ( ! empty( $form )
	     && check_admin_referer( 'intercessor_ajax_export', 'intercessor_ajax_export' ) ) {
*/

		if ( ! wp_verify_nonce( $_REQUEST['intercessor_ajax_export'], 'intercessor_ajax_export' ) ) {
			die( '-2' );
		}

		do_action( 'intercessor_batch_export_class_include', $form['intercessor-export-class'] );

		$step  = absint( $_POST['step'] );
		$class = sanitize_text_field( $form['intercessor-export-class'] );

		/** @var Intercessor\Admin\Tools\Export\Batch $export */
		$export = new $class( $step );

		if ( ! $export->can_export() ) {
			die( '-1' );
		}

		if ( ! $export->is_writable ) {
			echo wp_json_encode(
				array(
					'error'   => true,
					'message' => esc_html__( 'Export location or file not writable', 'intercessor' ),
				)
			);

			exit;
		}

		$export->set_properties( $_REQUEST );

		// Added in 0.9.5 to allow a bulk processor to pre-fetch some data to speed up the remaining steps and cache data.
		$export->pre_fetch();

		$ret        = $export->process_step();
		$percentage = $export->get_percentage_complete();

		if ( $ret ) {
			$step++;

			echo wp_json_encode(
				array(
					'step'       => $step,
					'percentage' => $percentage,
				)
			);

			exit;
		} elseif ( true === $export->is_empty ) {
			echo wp_json_encode(
				array(
					'error'   => true,
					'message' => esc_html__( 'No data found for export parameters', 'intercessor' ),
				)
			);

			exit;
		} elseif ( true === $export->done && true === $export->is_empty ) {
			$message = ! empty( $export->message )
				? $export->message
				: esc_html__( 'Batch Processing Complete', 'intercessor' );

			echo wp_json_encode( array(
				'success' => true,
				'message' => $message,
			) );

			exit;
		} else {
			$args = array_merge(
				$_REQUEST,
				array(
					'step'       	     => $step,
					'class'      	     => $class,
					'nonce'      	     => wp_create_nonce( 'intercessor-batch-export' ),
					'intercessor_action' => 'prayer_batch_export',
				)
			);

			$prayer_url = add_query_arg( $args, admin_url() );

			echo wp_json_encode(
				array(
					'step' => 'done',
					'url'  => $prayer_url,
				)
			);

			exit;
		}
//	}
}
add_action( 'wp_ajax_intercessor_do_ajax_export', 'intercessor_do_ajax_export' );
